version: '3'

services:

# container for python server
  py:
    build: 
      context: .
      dockerfile: python_image/Dockerfile

    depends_on:
      - mlflow_tracker

    image: mlflow_py_demo

    ports:
      - "8888:8888"

    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/opt/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"

    # command to start jupyter notebook server
    command: >
       jupyter notebook --no-browser --ip 0.0.0.0 
          --allow-root --password='' --NotebookApp.token=''
          --notebook-dir=/opt/project

# container for R server
  r:
    build: 
      context: .
      dockerfile: mlflow_r_image/Dockerfile

    depends_on:
      - mlflow_tracker

    image: mlflow_r_demo

    ports:
      - "8787:8787"

    environment:
      DISABLE_AUTH:  'true'
      MLFLOW_TRACKING_URI: "${MLFLOW_TRACKING_URI}"

    volumes:
      - "${MLFLOW_DEMO_DIRECTORY:-/tmp}:/home/rstudio/project"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"


###
# TO DISABLE DATABASE TRACKER COMPONENTS REMOVE
# OR COMMENT OUT ALL LINES FOLLOWING THIS COMMENT SECTION.
###


# container for mlflow_tracker - database
  mlflow_tracker:
    build:
      context: .
      dockerfile: mlflow_server/Dockerfile

    depends_on:
      - pgdb

    image: mlflow_server

    ports:
      - "5000:5000"

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/tracking:/tracking"
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/artifacts:/artifacts"


    command:
      - "/wait-for-pgdb.sh"
      - "mlflow server"
      - "--backend-store-uri ${MLFLOW_BACKEND_STORE}"
      - "--default-artifact-root /artifacts"
      - "--host 0.0.0.0"
      - "--port 5000"


# container for postgres database server
  pgdb:

    image: postgres:10

    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: mlflow_pw
      POSTGRES_USER: mlflow_user
      POSTGRES_DB: mlflow_db

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/postgres/data:/var/lib/postgresql/data"


# container for postgres admin server
  pgadmin:

    image: dpage/pgadmin4

    ports:
      - "80:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: "mlflow@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: pgadmin4

    volumes:
      - "${MLFLOW_TRACKING_DIRECTORY:-/tmp}/postgres/pgadmin:/var/lib/pgadmin"

